In [1]:
!pip install hidden_markov
from hidden_markov import hmm
import hidden_markov
import numpy as np

In [10]:
from hidden_markov import hmm
# h: healthy , i: ill
states = ('h', 'i')
# S: sleep, E: eat, A: Exercise
possible_observation = ('S', 'E', 'A')

# Initial Variables
start_probability = np.matrix('0.4 0.6')
transition_probability = np.matrix('0.5 0.5 ; 0.5 0.5')
emission_probability = np.matrix('0.3 0.3 0.4; 0.4 0.3 0.3')

In [11]:
# Baum-welch Algorithm with hidden_markov library

# Initialize the model
model = hmm(states, possible_observation, start_probability, transition_probability, emission_probability)
observations = [('E', 'A', 'E', 'S', 'S', 'E', 'A', 'E', 'S', 'S', 'A', 'E')]
quantities_observations = [1]

In [12]:
num_iter = 100
e, t, s = model.train_hmm(observations, num_iter, quantities_observations)

In [16]:
# Updated Emissions, Transitions, initial weights
e, t, s

(matrix([[0.29943918, 0.40244742, 0.29811339],
         [0.36533507, 0.43009201, 0.20457293]]),
 matrix([[0.49190056, 0.50809944],
         [0.4958507 , 0.5041493 ]]),
 matrix([[0.3944267, 0.6055733]]))