In [0]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split
import numpy as np

## Defining Dataset

In [0]:
class CustomDataset(Dataset):
  def __init__(self):
    super(CustomDataset, self).__init__()
    self.X = np.random.normal(size=(10, 4))
    self.y = np.random.randint(0, 2, size=(10))

  def __len__(self):
    return self.X.shape[0]  

  def __getitem__(self, idx):
    if torch.is_tensor(idx):
      idx = idx.tolist()
    return self.X[idx], self.y[idx]  


In [0]:
dataset = CustomDataset()

In [12]:
n = len(dataset)
t = int(0.2*n)
n

10

In [13]:
train_data, test_data = random_split(dataset, [n - t, t])
print('train', len(train_data), 'test', len(test_data))

train 8 test 2


In [14]:
dataset[0]

(array([ 0.85839299, -1.07032919,  0.3764086 ,  0.29744114]), 1)

In [0]:
loader = DataLoader(train_data, batch_size=2, shuffle=True)

In [18]:
for sample in loader:
  x, y = sample # each sample is a batch
  print(x, y)

tensor([[-0.6888, -0.5721, -0.3136,  0.1083],
        [ 0.5298, -0.7920, -0.6487, -3.1199]], dtype=torch.float64) tensor([1, 0])
tensor([[ 1.6323, -0.1540, -0.2973, -0.0287],
        [-0.3838,  0.8882,  1.0034,  1.4069]], dtype=torch.float64) tensor([0, 0])
tensor([[ 1.9535e+00,  1.7816e+00, -5.5459e-01,  8.9870e-01],
        [ 1.3476e-03, -4.5896e-01, -2.0015e-01, -1.2567e+00]],
       dtype=torch.float64) tensor([1, 0])
tensor([[-0.1459,  0.5260, -0.4491, -0.7840],
        [-0.5399,  1.2885, -2.0445, -0.7701]], dtype=torch.float64) tensor([1, 0])
