In [0]:
import torch
import numpy as np
from torch.autograd import Variable

## Tensors

In [26]:
a = np.zeros(shape=(3, 4))
print(a.dtype, type(a))
print(a)

float64 <class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
b = torch.zeros(3, 4, dtype=torch.int32)
print(b.dtype, type(b))
print(b)

torch.int32 <class 'torch.Tensor'>
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [28]:
# numpy to tensor
c = torch.tensor(a)
print(c.dtype, type(c))
print(c)

torch.float64 <class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [29]:
# tensor to numpy
b.numpy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

## Operations

In [30]:
print(torch.add(c, b))
print(b + c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [31]:
res = torch.empty(3,4) # empty allocates uninitialized memory
torch.add(b, c, out=res)
res

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# matrix multiplication with matmul or @

a = torch.randn(3,4)
b = torch.randn(3,)
c = torch.matmul(b,a)
c, b@a

(tensor([0.0463, 0.1905, 0.7493, 0.4941]),
 tensor([0.0463, 0.1905, 0.7493, 0.4941]))

In [49]:
# elementwise multiplication with *

b = torch.randn(3,4)
a*b

tensor([[-0.2980, -0.0230, -1.3218, -0.3907],
        [ 0.2460,  0.0313, -0.1977, -0.5207],
        [ 0.1350, -0.3312, -1.4784, -0.8640]])

## Resize

In [32]:
b.reshape(4, 3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [33]:
b.view(4, 3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [34]:
b.view(-1) # flatten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

## Moving tensor to gpu

In [35]:
b.cuda()

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], device='cuda:0', dtype=torch.int32)

In [36]:
b.device

device(type='cpu')

In [37]:
b.to('cuda:0')

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], device='cuda:0', dtype=torch.int32)

## Autograd

In [38]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [39]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [40]:
y.grad_fn

In [41]:
z = y.mean()
z

tensor(3., grad_fn=<MeanBackward0>)

In [0]:
z.backward()

In [43]:
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [0]:
x = x - 0.001 * x.grad

In [45]:
x

tensor([[0.9750, 0.9750],
        [0.9750, 0.9750]], grad_fn=<SubBackward0>)

In [46]:
# doesn't give error in inplace gradiant computation
X = Variable(torch.ones(2, 2), requires_grad=True)
X

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

## Manipulating tensor data

In [48]:
print(b)
b.data.fill_(2.)
b

tensor([-1.0732,  1.3933,  0.5972])


tensor([2., 2., 2.])